ASC.Web/Areas/ServiceRequests/Models/NewServiceRequestViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ASC.Web.Areas.ServiceRequests.Models
{
    public class NewServiceRequestViewModel
    {
        [Required]
        [Display(Name = "Vehicle Name")]
        public string VehicleName { get; set; }

        [Required]
        [Display(Name = "Vehicle Type")]
        public string VehicleType { get; set; }
        [Required]
        [Display(Name = "Requested Services")]
        public string RequestedServices { get; set; }
        [Required]
        [Display(Name = "Requested Date")]
        public DateTime? RequestedDate { get; set; }
    }
}

ASC.Web/Areas/ServiceRequests/Models/ServiceRequestMappingProfile.cs
using ASC.Model.Models;
using ASC.Web.Areas.ServiceRequests.Models;
using AutoMapper;

namespace ASC.Web.Areas.ServiceRequests.Models
{
    public class ServiceRequestMappingProfile : Profile
    {
        public ServiceRequestMappingProfile()
        {
            CreateMap<ServiceRequest, NewServiceRequestViewModel>();
            CreateMap<NewServiceRequestViewModel, ServiceRequest>();
        }
    }


}

ASC.Web/Areas/ServiceRequests/Controllers/ServiceRequestController.cs
using ASC.Business.Interfaces;
using ASC.Model.BaseTypes;
using ASC.Model.Models;
using ASC.Utilities;
using ASC.Web.Areas.ServiceRequests.Controllers;
using ASC.Web.Data;
using ASC.Web.Areas.ServiceRequests.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace ASC.Web.Areas.ServiceRequests.Controllers
{
    [Area("ServiceRequests")]
    public class ServiceRequestController : BaseController
    {
        private readonly IServiceRequestOperations _serviceRequestOperations;
        private readonly IMapper _mapper;
        private readonly IMasterDataCacheOperations _masterData;

        public ServiceRequestController(IServiceRequestOperations operations, IMapper mapper, IMasterDataCacheOperations masterData)
        {
            _serviceRequestOperations = operations;
            _mapper = mapper;
            _masterData = masterData;
        }

        [HttpGet]
        public async Task<IActionResult> ServiceRequest()
        {
            var masterData = await _masterData.GetMasterDataCacheAsync();
            ViewBag.VehicleTypes = masterData.Values.Where(p => p.PartitionKey == MasterKeys.VehicleType.ToString()).ToList();
            ViewBag.VehicleNames = masterData.Values.Where(p => p.PartitionKey == MasterKeys.VehicleName.ToString()).ToList();
            return View(new NewServiceRequestViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> ServiceRequest(NewServiceRequestViewModel request)
        {
            if (!ModelState.IsValid)
            {
                var masterData = await _masterData.GetMasterDataCacheAsync();
                ViewBag.VehicleTypes = masterData.Values.Where(p => p.PartitionKey == MasterKeys.VehicleType.ToString()).ToList();
                ViewBag.VehicleNames = masterData.Values.Where(p => p.PartitionKey == MasterKeys.VehicleName.ToString()).ToList();
                return View(request);
            }

            // Map the view model to Azure model
            var serviceRequest = _mapper.Map<NewServiceRequestViewModel, ServiceRequest>(request);

            // Set RowKey, PartitionKey, RequestedDate, Status properties
            serviceRequest.PartitionKey = HttpContext.User.GetCurrentUserDetails().Email;
            serviceRequest.RowKey = Guid.NewGuid().ToString();
            serviceRequest.RequestedDate = request.RequestedDate;
            serviceRequest.Status = Status.New.ToString();

            await _serviceRequestOperations.CreateServiceRequestAsync(serviceRequest);
            return RedirectToAction("Dashboard", "Dashboard", new { Area = "ServiceRequests" });
        }
    }

}

ASC.Web/Areas/ServiceRequests/Views/ServiceRequest/ServiceRequest.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
﻿
@model ASC.Web.Areas.ServiceRequests.Models.NewServiceRequestViewModel
@using System.Globalization
@{
    Layout = "_SecureLayout";
}

<div class="row"></div>
<div class="row padding-top-20px padding-left-20px padding-right-20px">
    @* Details Section *@
    <div class="row z-depth-3">
        <div class="col s12 padding-0px">
            <div class="section white-text padding-left-10px blue-grey lighten-1">
                <h5>New Service Request</h5>
            </div>
            <div class="divider"></div>
            <form asp-controller="ServiceRequest" asp-action="ServiceRequest" method="post"
                  class="col s12">
                <div class="row">
                    <div class="input-field col s4">
                        <select asp-for="VehicleName" asp-items="@(new SelectList(ViewBag.VehicleNames, "RowKey", "Name"))" class="" required="required">
                            <option value="">Please select one</option>
                        </select>
                        <label asp-for="VehicleName"></label>
                    </div>
                    <div class="input-field col s4">
                        <select asp-for="VehicleType" asp-items="@(new SelectList(ViewBag.VehicleTypes, "RowKey", "Name"))" class="validate" required="required">
                            <option value="">Please select one</option>
                        </select>
                        <label asp-for="VehicleType"></label>
                    </div>
                    <div class="input-field col s4">
                        <input asp-for="RequestedDate" type="text" class="datepicker">
                        <label asp-for="RequestedDate"></label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s8">
                        <textarea asp-for="RequestedServices" class="materialize-textarea validate"></textarea>
                        <label asp-for="RequestedServices"></label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 right-align">
                        <button class="btn waves-effect waves-light btnSubmit" type="submit"
                                name="action">
                            Create
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                    <div class="row col s12 right-align" asp-validation-summary="All"></div>
                </div>
            </form>
        </div>
        <div class="row"></div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy'
            });

            $('select').formSelect();
            $("select[required]").css({ display: "block", position: 'absolute', visibility: 'hidden' });
        });
    </script>
}